[package]
name = "environment-variables"
description = "The project shows how to use [config](https://docs.rs/config/latest/config/) crate to manage environment variables."
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.1"
dotenvy = "0.15.7"
serde = "1.0.215"
