[package]
name = "grep"
description = "The project implements the basic functionality of the grep tool. It was created while going through [The Rust Programming Language](https://doc.rust-lang.org/book/ch12-00-an-io-project.html) book."
version = "0.1.0"
edition = "2021"

[dependencies]
