[package]
name = "docgen"
description = "The project is a documentation generator. It generates this readme.md file."
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
